name: Build and Publish image to Docker Hub

on:
  [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4    
    - name: build the docker image
      run: docker build -f ./Shopping/Shopping.Client/Dockerfile -t allbertoeng/shoppingapp:latest .
    - name: log in to docker hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    - name: push image    
      run: docker push allbertoeng/shoppingapp:latest
